[package]
name = "reverse_polish_calculator"
version = "0.1.0"
authors = ["eoanermine"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
